import Head from "next/head";
import { useRouter } from "next/router";
import { useContext, useEffect } from "react";
import { PreguntasContext } from "../context/PreguntasProvider";
import { RiQuestionnaireFill } from "react-icons/ri";
import styles from "../styles/Home.module.css";

export default function Home() {
  const context = useContext(PreguntasContext);
  const { preguntas, setPreguntasOrdenadas, preguntasOrdenadas, randomOrder } =
    context;
  const router = useRouter();
  useEffect(() => {
    let randomPreguntas = randomOrder(preguntas);
    const newOrdenadas = [];

    for (let i = 0; i < randomPreguntas.length; i++) {
      newOrdenadas.push({ orden: i + 1, ...randomPreguntas[i] });
    }

    setPreguntasOrdenadas(newOrdenadas);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Quiz Copade</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-center items-center h-screen">
        <div className="grid grid-rows-2 place-items-center">
          <h1 className="md:text-4xl text-xl font-bold text-emerald-800 w-full">
            Bienvenidos a Quiz app <RiQuestionnaireFill className="inline" />
          </h1>
          <button
            onClick={() => {
              router.push("/quiz");
            }}
            className="btn bg-emerald-500 w-2/3 p-4 font-bold rounded text-white mt-4"
          >
            Comenzar!
          </button>
        </div>
      </main>
    </div>
  );
}
